language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
sudo: false
install:
  - bash scripts/install.sh
script:
  - python scripts/run-tests.py
after_success:
  - python-codacy-coverage -r coverage.xml
